# Generated by Django 5.2.3 on 2025-07-09 07:13

import django.db.models.deletion
import django.utils.timezone
import websites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='使用條款', max_length=200, verbose_name='條款標題')),
                ('content', models.TextField(verbose_name='條款內容（Markdown格式）')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='版本號')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否為最新版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '使用條款',
                'verbose_name_plural': '使用條款',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容（Markdown格式）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否為重要公告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始顯示時間')),
                ('end_date', models.DateTimeField(blank=True, default=websites.models.get_default_end_date, null=True, verbose_name='結束顯示時間（預設三天後失效）')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '全站公告',
                'verbose_name_plural': '全站公告',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTermsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='同意時間')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='瀏覽器資訊')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.terms', verbose_name='條款')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者條款同意記錄',
                'verbose_name_plural': '使用者條款同意記錄',
                'ordering': ['-agreed_at'],
                'unique_together': {('user', 'terms')},
            },
        ),
    ]
