# Generated by Django 5.2.3 on 2025-07-09 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '對話會話',
                'verbose_name_plural': '對話會話',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], db_index=True, default='completed', max_length=16)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('tool', 'Tool')], db_index=True, default='user', max_length=16)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], db_index=True, default='text', max_length=16)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('file_url', models.URLField(blank=True, default=None, null=True)),
                ('file_path', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('traceback', models.TextField(blank=True, default=None, null=True)),
                ('references', models.JSONField(blank=True, default=None, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=64)),
                ('tool_keywords', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='軟刪除標記')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='conversations.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.session')),
            ],
            options={
                'verbose_name': '對話訊息',
                'verbose_name_plural': '對話訊息',
                'ordering': ['-updated_at'],
            },
        ),
    ]
