# Generated by Django 5.2.3 on 2025-07-09 07:13

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '自建資料源',
                'verbose_name_plural': '自建資料源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.FloatField(help_text='檔案大小，單位為 MB')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='使用 OpenAI text-embedding-3-small 產生向量。')),
                ('path', models.CharField(blank=True, help_text='檔案路徑，用於儲存上傳的檔案，格式為 /<指定目錄>/<a~z>(username 首字小寫)/<username>/<uuid>.<format>', max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='檔案唯一 ID')),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('processing', '處理中'), ('completed', '處理完成'), ('failed', '處理失敗')], default='pending', max_length=20)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '資料源檔案',
                'verbose_name_plural': '資料源檔案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='使用 OpenAI text-embedding-3-small 產生向量。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.sourcefile')),
                ('source_file_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_source_file_chunks', to='sources.sourcefilechunk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '資料源檔案片段',
                'verbose_name_plural': '資料源檔案片段',
            },
        ),
        migrations.CreateModel(
            name='SourceFileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('database_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.sourcefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '資料源檔案表格',
                'verbose_name_plural': '資料源檔案表格',
            },
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['summary_embedding'], m=16, name='file_summary_embedding_hnsw_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='sourcefilechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['content_embedding'], m=16, name='file_chunk_embedding_hnsw_idx', opclasses=['vector_l2_ops']),
        ),
    ]
